import Head from 'next/head';
import { Inter } from 'next/font/google';
import { GetServerSidePropsContext } from 'next';
import Main from '@/component/main';
import styled from 'styled-components';
import { getStyledThemProperty } from '@/shared/styles/util';

const inter = Inter({ subsets: ['latin'] });

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function Home() {
  // function kakaoInit() {
  //   window.Kakao.init(process.env.NEXT_PUBLIC_KAKAO_CLIENT_ID);
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainWrap>
        <Main />
      </MainWrap>
    </>
  );
}

const MainWrap = styled.div`
  height: 100%;
  ${getStyledThemProperty('box', 'flexCenterBox')};
  flex-direction: column;
`;

export const getServerSideProps = async ({
  req,
  res,
  ...rest
}: GetServerSidePropsContext) => {
  return {
    props: {},
  };
};
